# theme: jekyll-theme-minimal
theme: github-pages-minimal
url: https://drolsonmi.github.io
markdown: kramdown
kramdown:
  #input: GFM
  math_engine: mathjax
  # math_engine: katex
  syntax_highlighter: rouge
usemathjax: true

sidebar:
  - 18-3